[workspace]
members = [
    "algorithms/lyt15-cpp-wrapper",
    "algorithms/miz23-md-cpp-sys",
    "algorithms/miz23-md-cpp",
    "algorithms/miz23-md-rs",
    "algorithms/ms00",
    "common",
    "hippodrome",
    "playground",
]
resolver="2"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
petgraph = "0.6.3"
