[workspace]
members = [
    "algorithms/miz23-md-cpp-sys",
    "algorithms/miz23-md-cpp",
    "algorithms/miz23-md-rs",
    "algorithms/ms00",
    "common",
    "hippodrome",
    "playground",
]
resolver="2"
