[workspace]
members = [
#    "algorithms/dgm01",
#    "algorithms/jsc72",
#    "algorithms/kar19-jl",
    "algorithms/kar19-rs",
    "algorithms/lyt15-cpp-wrapper",
#    "algorithms/lyt15-rs",
    "algorithms/miz23-md-cpp-sys",
    "algorithms/miz23-md-cpp",
    "algorithms/miz23-md-rs",
    "algorithms/ms00",
    "common",
    "hippodrome",
    "playground",
]
resolver="2"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
petgraph = "0.6.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.0"
